#!/bin/sh

# A qick and dirty shuffle FX generator for the ZFXB3 using shuf from GNU coreutils.
# On macOS you can install coreutils via brew, but than you have to call gshuf, wtf.
# Work in progress.
 
# Script handling:
# Protect scripts (errexit -e, nounset -u, noglob -f)
set -euf
# Bash
#set -euf -o posix -o pipefail

usage() {
  printf "%s\n" "Usage: $0 [-h] [-v] [-b bank]"
  printf "%s\n" "  -b  Add on. Select bank (A0 - J9). Need capital letters. Works only from A0 to F9 at the moment."
  printf "%s\n" "  -h  Help. Display this message and quit."
  printf "%s\n" "  -f  Fill all banks with randon data."
  printf "%s\n" "  -p  Specify a hardware port, e.g. hw:2,0,0 or simply hw:2"
  printf "%s\n" "  -r  Add on. Reset changes from the preset and quit. Works from time to time." #(?Not inside Total-/Globalmodus)
  printf "%s\n" "  -s  Add on. Flip signal chain path forward/backward. (0 / 1)"
  printf "%s\n" "  -v  Version. Print version number and quit."
  exit
}

version() { 
  printf "%s\n" "0.00.003 alpha"
  exit 
}

fill() {
  set +u
  if [ -z "$port" ]; then
    port=$(amidi -l | tail -n 1 | cut -d " " -f 3) 
  fi
  set -u
  i=0
  while [ "$i" -lt '100' ]; do
  varh=$(printf "%X\n" "$i")
  # Change Patch from A0 to J9:
  amidi -p "$port" -S "C0 $varh" -i 0.01
  # Not working in mrsh. Expected done.
  i=$(((i + 1)))
  # Not working in zsh. Want call fill
  sh "$0"
  done
}

shuffx() {
  printf "%X\n" "$(shuf -i 1-111 -n 1)"
#  tools/test/go/bin/zoofxshuffler --min=1 --max=111
}

shuftemp0() {
  printf "%X\n" "$(shuf -i 40-127 -n 1)"
#  tools/test/go/bin/zoofxshuffler --min=40 --max=127
}

shuftemp1() {
  printf "%X\n" "$(shuf -i 0-122 -n 1)"
#  tools/test/go/bin/zoofxshuffler --min=0 --max=122
}

shufbar() {
  printf "%s\n" "$(shuf -i 0-1 -n 1)"
#  tools/test/go/bin/zoofxshuffler --min=0 --max=1
}

shufname() {
  printf "%s\n" "$(shuf -i 48-57 -n 1)"
#  tools/test/go/bin/zoofxshuffler --min=48 --max=57
}


shufknob() {
  select=$(printf "%X\n" "$(shuf -i 0-17 -n 1)")
  case "$select" in
     '0') printf "%X\n" "$(shuf -i 32-64  -n 1)"  ;;
     '1') printf "%X\n" "$(shuf -i 3-47   -n 1)"  ;;
     '2') printf "%X\n" "$(shuf -i 0-100  -n 1)"  ;;
     '3') printf "%X\n" "$(shuf -i 4-12   -n 1)"  ;;
     '4') printf "%X\n" "$(shuf -i 10-42  -n 1)"  ;;
     '5') printf "%X\n" "$(shuf -i 0-9    -n 1)"  ;;
     '6') printf "%X\n" "$(shuf -i 10-19  -n 1)"  ;;
     '7') printf "%X\n" "$(shuf -i 7-32   -n 1)"  ;;
     '8') printf "%X\n" "$(shuf -i 30-64  -n 1)"  ;;
     '9') printf "%X\n" "$(shuf -i 15-21  -n 1)"  ;;
    '10') printf "%X\n" "$(shuf -i 50-100 -n 1)"  ;;
    '11') printf "%X\n" "$(shuf -i 16-72  -n 1)"  ;;
    '12') printf "%X\n" "$(shuf -i 12-48  -n 1)"  ;;
    '13') printf "%X\n" "$(shuf -i 80-90  -n 1)"  ;;
    '14') printf "%X\n" "$(shuf -i 42-78  -n 1)"  ;;
    '15') printf "%X\n" "$(shuf -i 0-16   -n 1)"  ;;
    '16') printf "%X\n" "$(shuf -i 70-90  -n 1)"  ;;
    '17') printf "%X\n" "$(shuf -i 0-10   -n 1)"  ;;
   esac
}


#shufknob() {
#  select=$(tools/test/go/bin/zoofxshuffler --min=0 --max=17)
#  case "$select" in
#    '00') tools/test/go/bin/zoofxshuffler --min=32  --max=64   ;;
#    '01') tools/test/go/bin/zoofxshuffler --min=3   --max=47   ;;
#    '02') tools/test/go/bin/zoofxshuffler --min=0   --max=100  ;;
#    '03') tools/test/go/bin/zoofxshuffler --min=4   --max=12   ;;
#    '04') tools/test/go/bin/zoofxshuffler --min=10  --max=42   ;;
#    '05') tools/test/go/bin/zoofxshuffler --min=0   --max=9    ;;
#    '06') tools/test/go/bin/zoofxshuffler --min=10  --max=19   ;;
#    '07') tools/test/go/bin/zoofxshuffler --min=7   --max=32   ;;
#    '08') tools/test/go/bin/zoofxshuffler --min=30  --max=64   ;;
#    '09') tools/test/go/bin/zoofxshuffler --min=15  --max=21   ;;
#    '0A') tools/test/go/bin/zoofxshuffler --min=50  --max=100  ;;
#    '0B') tools/test/go/bin/zoofxshuffler --min=16  --max=72   ;;
#    '0C') tools/test/go/bin/zoofxshuffler --min=12  --max=48   ;;
#    '0D') tools/test/go/bin/zoofxshuffler --min=80  --max=90   ;;
#    '0E') tools/test/go/bin/zoofxshuffler --min=42  --max=78   ;;
#    '0F') tools/test/go/bin/zoofxshuffler --min=0   --max=16   ;;
#    '10') tools/test/go/bin/zoofxshuffler --min=70  --max=90   ;;
#    '11') tools/test/go/bin/zoofxshuffler --min=0   --max=10   ;;
#   esac
#}

bank=""
optspec="p:b:hfvs:"
while getopts "$optspec" optchar
do
    case "${optchar}" in
        'p')  
            port=${OPTARG}
            ;;
        'b')
            bank="$OPTARG"
            set +u
            if [ -z "$port" ]; then
              port=$(amidi -l | tail -n 1 | cut -d " " -f 3)
            fi
            set -u
            printf "%s\n" "$bank"
            # not working in mrsh
            bankd=$(printf "%d\n" "0x$bank")
            printf "%s\n" "bankd: $bankd" 
            banks=$((bankd - 160))
            printf "%s\n" "banks: $banks"
            varc=$(printf "%X\n" "$banks")
            printf "%s\n" "varc: $varc"
            varh=$(printf "%X\n" "$varc")
            printf "%s\n" "varh: $varh"
	    amidi -p "$port" -S "C0 $varh"
	    ;;
        'h')
            usage
            ;;
        'f')
            printf "%s\n" "This will override all banks with random data. All data will be lost."
            printf "%s\n" "You should make a backup before you proceed!"
            printf "%s" "Are you sure? (y/N)?"
            read -r answer
            if [ "$answer" != "${answer#[Yy]}" ]; then
              fill
            else
              exit 23
            fi
            ;;
        's')
            flip=${OPTARG}
            set +u
            if [ -z "$port" ]; then
              port=$(amidi -l | tail -n 1 | cut -d " " -f 3) 
            fi
            set -u
            # change 4F to mod
	    amidi -p "$port" -S "F0 52 00 4F 50 F7" && amidi -p "$port" -S "F0 52 00 4F 31 03 09 $flip 00 F7" \
            && amidi -p "$port" -S "F0 52 00 4F 51 F7" 
            ;;
        'v')
            version
            ;;
        *)
            usage
            ;;
    esac
done

set +u
if [ -z "$port" ]; then
  port=$(amidi -l | tail -n 1 | cut -d " " -f 3) 
fi
set -u

# Identify device
id=$(amidi -p "$port" -S "F0 7E 00 06 01 F7" -d -t 0.4 | tail -n 1)

# Model ID
mod=$(printf "%s\n" "$id" | cut -c 19-21)

# Unlock device
#printf "%s\n" "Open Sesame!"
amidi -p "$port" -S "F0 52 00 $mod 50 F7" -i 0.01

# Shuffle
# Module0 left
amidi -p "$port" -S "F0 52 00 $mod 31 00 01 $(shuffx) 00 F7" -i 0.01

# Module1 middle
amidi -p "$port" -S "F0 52 00 $mod 31 01 01 $(shuffx) 00 F7" -i 0.01

# Module2 right
amidi -p "$port" -S "F0 52 00 $mod 31 02 01 $(shuffx) 00 F7" -i 0.01

# Stompbar
a=$(shufbar)
b=$(shufbar)
c=$(shufbar)
while [ "$a" -eq '0' ] && [ "$b" -eq '0' ] && [ "$c" -eq '0' ]; do
  a=$(shufbar)
  b=$(shufbar)
  c=$(shufbar)
done

# Stompbar Module0 left:             
amidi -p "$port" -S "F0 52 00 $mod 31 00 00 $a 00 F7" -i 0.01

# Stompbar Module1 middle:             
amidi -p "$port" -S "F0 52 00 $mod 31 01 00 $b 00 F7" -i 0.01

# Stompbar Module1 right:             
amidi -p "$port" -S "F0 52 00 $mod 31 02 00 $c 00 F7" -i 0.01

# Knobs Module0 left Knob1 left page1:
amidi -p "$port" -S "F0 52 00 $mod 31 00 02 $(shufknob) 00 F7" -i 0.01
# Knobs Module0 left Knob2 middle page1:
amidi -p "$port" -S "F0 52 00 $mod 31 00 03 $(shufknob) 00 F7" -i 0.01
# Knobs Module0 left Knob3 right page1:
amidi -p "$port" -S "F0 52 00 $mod 31 00 04 $(shufknob) 00 F7" -i 0.01
# Knobs Module0 left Knob1 left page2:
amidi -p "$port" -S "F0 52 00 $mod 31 00 05 $(shufknob) 00 F7" -i 0.01
# Knobs Module0 left Knob2 middle page2:
amidi -p "$port" -S "F0 52 00 $mod 31 00 06 $(shufknob) 00 F7" -i 0.01
# Knobs Module0 left Knob3 right page2:
amidi -p "$port" -S "F0 52 00 $mod 31 00 07 $(shufknob) 00 F7" -i 0.01
# Knobs Module0 left Knob1 left page3:
amidi -p "$port" -S "F0 52 00 $mod 31 00 08 $(shufknob) 00 F7" -i 0.01
# Knobs Module0 left Knob2 middle page3:
amidi -p "$port" -S "F0 52 00 $mod 31 00 09 $(shufknob) 00 F7" -i 0.01
# Knobs Module0 left Knob3 right page3:
amidi -p "$port" -S "F0 52 00 $mod 31 00 0A $(shufknob) 00 F7" -i 0.01

# Knobs Module1 left Knob1 left page1:
amidi -p "$port" -S "F0 52 00 $mod 31 01 02 $(shufknob) 00 F7" -i 0.01
# Knobs Module1 left Knob2 middle page1:
amidi -p "$port" -S "F0 52 00 $mod 31 01 03 $(shufknob) 00 F7" -i 0.01
# Knobs Module1 left Knob3 right page1:
amidi -p "$port" -S "F0 52 00 $mod 31 01 04 $(shufknob) 00 F7" -i 0.01
# Knobs Module1 left Knob1 left page2:
amidi -p "$port" -S "F0 52 00 $mod 31 01 05 $(shufknob) 00 F7" -i 0.01
# Knobs Module1 left Knob2 middle page2:
amidi -p "$port" -S "F0 52 00 $mod 31 01 06 $(shufknob) 00 F7" -i 0.01
# Knobs Module1 left Knob3 right page2:
amidi -p "$port" -S "F0 52 00 $mod 31 01 07 $(shufknob) 00 F7" -i 0.01
# Knobs Module1 left Knob1 left page3:
amidi -p "$port" -S "F0 52 00 $mod 31 01 08 $(shufknob) 00 F7" -i 0.01
# Knobs Module1 left Knob2 middle page3:
amidi -p "$port" -S "F0 52 00 $mod 31 01 09 $(shufknob) 00 F7" -i 0.01
# Knobs Module1 left Knob3 right page3:
amidi -p "$port" -S "F0 52 00 $mod 31 01 0A $(shufknob) 00 F7" -i 0.01

# Knobs Module2 left Knob1 left page1:
amidi -p "$port" -S "F0 52 00 $mod 31 02 02 $(shufknob) 00 F7" -i 0.01
# Knobs Module2 left Knob2 middle page1:
amidi -p "$port" -S "F0 52 00 $mod 31 02 03 $(shufknob) 00 F7" -i 0.01
# Knobs Module2 left Knob3 right page1:
amidi -p "$port" -S "F0 52 00 $mod 31 02 04 $(shufknob) 00 F7" -i 0.01
# Knobs Module2 left Knob1 left page2:
amidi -p "$port" -S "F0 52 00 $mod 31 02 05 $(shufknob) 00 F7" -i 0.01
# Knobs Module2 left Knob2 middle page2:
amidi -p "$port" -S "F0 52 00 $mod 31 02 06 $(shufknob) 00 F7" -i 0.01
# Knobs Module2 left Knob3 right page2:
amidi -p "$port" -S "F0 52 00 $mod 31 02 07 $(shufknob) 00 F7" -i 0.01
# Knobs Module2 left Knob1 left page3:
amidi -p "$port" -S "F0 52 00 $mod 31 02 08 $(shufknob) 00 F7" -i 0.01
# Knobs Module2 left Knob2 middle page3:
amidi -p "$port" -S "F0 52 00 $mod 31 02 09 $(shufknob) 00 F7" -i 0.01
# Knobs Module2 left Knob3 right page3:
amidi -p "$port" -S "F0 52 00 $mod 31 02 0A $(shufknob) 00 F7" -i 0.01

# Tempo
d=$(shufbar)
if [ "$d" -eq '0' ]; then
  amidi -p "$port" -S "F0 52 00 $mod 31 03 08 $(shuftemp0) 00 F7" -i 0.01
else
  amidi -p "$port" -S "F0 52 00 $mod 31 03 08 $(shuftemp1) 01 F7" -i 0.01
fi

# Display name ShufflePnP
amidi -p "$port" -S "F0 52 00 $mod 31 04 00 50 00 F7" -i 0.01
amidi -p "$port" -S "F0 52 00 $mod 31 04 01 6E 00 F7" -i 0.01
amidi -p "$port" -S "F0 52 00 $mod 31 04 02 50 00 F7" -i 0.01
amidi -p "$port" -S "F0 52 00 $mod 31 04 03 2D 00 F7" -i 0.01
amidi -p "$port" -S "F0 52 00 $mod 31 04 04 $(shufname) 00 F7" -i 0.01
amidi -p "$port" -S "F0 52 00 $mod 31 04 05 $(shufname) 00 F7" -i 0.01
amidi -p "$port" -S "F0 52 00 $mod 31 04 06 $(shufname) 00 F7" -i 0.01
amidi -p "$port" -S "F0 52 00 $mod 31 04 07 $(shufname) 00 F7" -i 0.01
amidi -p "$port" -S "F0 52 00 $mod 31 04 08 $(shufname) 00 F7" -i 0.01
amidi -p "$port" -S "F0 52 00 $mod 31 04 09 $(shufname) 00 F7" -i 0.01


#sleep 6
# Lock device again:
#amidi -p "$port" -S "F0 52 00 $mod 51 F7"



